name: Build Minecraft Mod

on:
  # Run automatically on push to main and pull requests
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java 8 (Forge 1.8.9 requires Java 8)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. Give gradlew permission to run
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. Run Gradle build
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      # 5. Upload the built mod JAR file
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
