name: Build Minecraft Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your plugin code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java 8 (needed for 1.8.8)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # Download and run Spigot BuildTools to install spigot-1.8.8 into local Maven repo
      - name: Install Spigot 1.8.8 to Maven local
        run: |
          mkdir buildtools
          cd buildtools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.8.8
          cd ..

      # Build your plugin
      - name: Build with Maven
        run: mvn clean package

      # Upload the built JAR
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: target/*.jar
