name: Build Minecraft Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 8 (Forge 1.8.9 requires Java 8)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. Build the mod
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      # 5. Upload the built JAR
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
